apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: introspect-hpa
spec:
  maxReplicas: 8
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: introspect
  targetCPUUtilizationPercentage: 50
