apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

bases:
- ./crd/
- ./rbac/
- ../mongodb

# list of Resource Config to be Applied
resources:
- namespace.yaml
- config.yaml
- deployment.yaml
- service.yaml
- istio.yaml
# - uselessmachine-1.yaml
# - uselessmachine-2.yaml


# labels added to all Resources
commonLabels:
  app: introspect
