apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- ./mongodb
- ./introspect
- ./istio

images:
- name: vasu1124/introspect:1.0.0
  newName: vasu1124/introspect
  newTag: "1.0.0"
- name: bitnami/mongodb:latest
  newName: bitnami/mongodb
  newTag: "latest"