apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: uselessmachines.introspect.actvirtual.com
spec:
  group: introspect.actvirtual.com
  names:
    kind: UselessMachine
    listKind: UselessMachineList
    plural: uselessmachines
    singular: uselessmachine
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: defines the desired state of a UselessMachine
            properties:
              desiredState:
                enum:
                - "On"
                - "Off"
                type: string
            required:
            - desiredState
            type: object
          status:
            properties:
              actualState:
                enum:
                - "On"
                - "Off"
                type: string
              message:
                type: string
            type: object
        type: object
    additionalPrinterColumns:
    - description: Desired state
      jsonPath: .spec.desiredState
      name: Desired
      type: string
    - description: Actual state
      jsonPath: .status.actualState
      name: Actual
      type: string
    - description: Controller message
      jsonPath: .status.message
      name: Message
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date

