apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: introspect-validationwebook
webhooks:
  - name: introspect.default.svc
    namespaceSelector:
      matchLabels:
        validation: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "Namespaced"
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU4akNDQXRxZ0F3SUJBZ0lKQUlmZTdpMHA0NGhmTUEwR0NTcUdTSWIzRFFFQkN3VUFNQlV4RXpBUkJnTlYKQkFNTUNtbHVkSEp2YzNCbFkzUXdIaGNOTWpFd09ESTRNVGd3TURJNFdoY05NekV3T0RJMk1UZ3dNREk0V2pBVgpNUk13RVFZRFZRUUREQXBwYm5SeWIzTndaV04wTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDCkNnS0NBZ0VBMkcrQ2lrY05hVXEyWmRkK2pJeFBjVFFYMEFKVmk4bUlYTXhqcU9sRlJybk91bnZtbVg4dm9RL0IKOWVzNVY1Tm4vZng5VElmell4SU9haHUvRHdBRU1UVXlvS1B0TWJIaGlmRTllNnJWbEdCYThuM3k2VDN6UVR5eAo4Njlrdi9LcCtIbjFnZUhBcUpIT21lWFBmL1RpWlZvaDF4UlRod3U0OUNFdVJrN3dad2Z6RzRjdWpPbC9KNm1mCktMWU1BSVkxcnZxbUxuVEV5Z3YrY01LRHJnN2NETkNPUWdaKzdGek1mWWNISzE3WGRRU2lTNFNBTVRJRnFUVjUKcnQ2azFyMHdlK0ZYZGxnazYvNTZxV0RvODlrWklkUmRvV3dqWHNoWE9WV0g3aFdhb1hxSlMxOWdZNlp2ajl4YQpaMHZmZEFXRi9pS3YwbTNoOXJsUFdrNkpWcWVXN2RRdUJFVWZDbWNwMVFCWTJBSk5LUWpRVGwreDZpK1NFeld5Cm1BM2dWM1Y0RHRBZkFvbXhKU1Y1NjA4TkU0OUpwZjlNZlFxa0orZC82VXRSQWpING5aRzFKSVVWZ21tZ0xXSFUKWnNRSWxsNzFMU21HckovNUxpSmF2ZXF1T2Qzc09JQllXNDNCbXJDdnJxb091WENtWHVuakF0RUpLK0tmNktjNgpmWHcyaUhHU2s4UzZtS1kxNGNJV3FraWs1UVJuSmlCTHUveXRkeE9WRjFCWlVGQlI0ZkpYQTRjUzJ0d1BZejhyCmNLZ2ExN3RvQWFDY3AzblcwaytyRGdzdTNEcWJEWHcreTVhUnZsZ3p3b3VzTXk3dUJ2YU4wVC9CQm43RkgyRk8KOHZvTE0xU3UxSWxnMmtrZlZSQS9BYUplVUljNm56RnNsbVV0M3ZNd1IwVWIvZ2graDQwQ0F3RUFBYU5GTUVNdwpRUVlEVlIwUkJEb3dPSUlLYVc1MGNtOXpjR1ZqZElJU2FXNTBjbTl6Y0dWamRDNWtaV1poZFd4MGdoWnBiblJ5CmIzTndaV04wTG1SbFptRjFiSFF1YzNaak1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQ29KUDNSdEdDc0xXWkgKcU5VSUJmcTdxVE4xb2hzejJSNTFNOExNRlVsWk9ZMUpXbDB4VGd0YlRBeGJxUEVwOGYrUTlKZmZPSW0vRnlOYwpYN1dwQ2xEZVh0bDJkUmxwYjRUcTBsc2pDcmtQd0VSNkdEeXpmZXJuNGlndlMvenhMTEpxMEs2MldBNmVKNWNpCnJDVUYrYUlSZG5USHc1SThTZWttbU9NZGNxN0o1NFU4WDgxNE9lNThtUk9ROWhVRzRZQ3VXOFVVai9JYldnRGsKVWZyMzRuNzBqeExKdzVBMEx5T2FSV0RHZCtTVVYxcWxWYWhVZ1luM2ZGUFViaE9wb3JnalhWKytYeDdHejVmNwpaeUNNbTlkMzF5L1B6aFEyMk1DNWR2RDVEZVppVnIyYVE5QzRJVmhYSjM2YUs0azBzbFhHTGF1WnNxRndkNk9jCjc0eWVPcTk0VmJzUHJ0T3UrYXArNndTblpFK1pJa1g0ZGt0L3dQdHN2ODBRdUVVOEpTRGNtZXAxaFlYYW1rWXMKVXVmQWR4bGU0M0FJZms4YUVQY01yY1lrRjh1TlJxNUtVL21wSEFoOUQ1WlhRbzRrMFJzTUFrY2xXY3BMcXlEbgpQYklETFlaa3dObzQ1ajBUMGVRWDR2Z0ExMWJNS3RSMnJ5S1dXZGowUUorY0tHTkhvOTh6eTVaUjUrblRYZUluCnFBMzVaS0N2UU5JVm5QNWN1SjN1TmZPb2lYSFZhUklsTXA0OHpHRGo0MU83c0xsdHk1QUNPSkNtWGEzSWFnUXQKc1RiVGtzK2o3dTZqdXQ0Q3lBTU9vWHkreDNDejhiM1JDSHdsOVV2cjdBOXRDWnBPYVBDS0ZUWEhiY1RmeWFudgpUUHAycmE4cHJnTi9rWHFGSE1mY20xVElMWmhBMkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: introspect
        namespace: default
        path: "/validate"
        port: 9443
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 10
    failurePolicy: Ignore
