apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- pvc.yaml
- secret.yaml
- deployment.yaml
- service.yaml


# labels added to all Resources
commonLabels:
  app: mongodb
