apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: demo
spec:
  profile: demo
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: false
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
          - name: http2
            port: 80
            targetPort: 8080
          - name: https
            port: 443
            targetPort: 8443
        serviceAnnotations:
          dns.gardener.cloud/dnsnames: "*.bnerd4.actvirtual.com"
          dns.gardener.cloud/ttl: "300" 
          dns.gardener.cloud/class: garden
          cert.gardener.cloud/issuer: "actvirtual.com"
          cert.gardener.cloud/secretname: wildcard-tls
  meshConfig:
    accessLogFile: /dev/stdout
