apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- Base/Base.yaml
- Base/Pilot/Pilot.yaml
- Base/Pilot/Cni/Cni.yaml
- Base/Pilot/EgressGateways/EgressGateways.yaml
- Base/Pilot/IngressGateways/IngressGateways.yaml
- Gateway.yaml
- IstioOperator.yaml