
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: introspect-role
rules:
- apiGroups:
  - introspect.actvirtual.com
  resources:
  - uselessmachines
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - introspect.actvirtual.com
  resources:
  - uselessmachines/status
  verbs:
  - update
  - patch
- apiGroups:
  - introspect.actvirtual.com
  resources:
  - uselesses
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - introspect.actvirtual.com
  resources:
  - uselesses/status
  verbs:
  - update
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  - configmaps
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete